### ISSUE TITLE
Accessing the selected-changed Event in Tabs?

### ISSUE THREAD

**Issue by frastlin** [tomivirkki/react-vaadin-components#10]
Hello,
I'm trying to access the selected-changed event from the [Tabs API.}(https://vaadin.com/components/vaadin-tabs/html-api/elements/Vaadin.TabsElement)

```
<Tabs selected-changed={()=>alert("ran")}>

<Tabs selectedChanged={()=>alert("ran")}>
```

and several other combos didn't work. Do you know how I access this event?
Thank you,

**Comment by tomivirkki** [comment]
Hi, `onSelectedChanged={()=> alert("ran")}` should work. The convention is mention under "Binding Events and Properties" in https://tomivirkki.github.io/react-vaadin-components/#/tutorial
