### ISSUE TITLE
Cannot use material-ui react components in GridColumn renderer

### ISSUE THREAD

**Issue by mira-t** [tomivirkki/react-vaadin-components#11]
I am using react-vaadin components solely because I needed a more suitable grid component compared to what is offered in the react material-ui package. I am trying to use a GridColumn with a renderer to put clickable icons in a column. When my renderer returns intrinsic components, it is fine, but when it returns an IconButton from @material-ui/core, I get an 'Invalid hook call' error. I'm guessing this is because a regular javascript function tries to use the component returned by the renderer? Is there a way to get around this? Or does this fall too far outside of the intended use case and I should use another package to create a table/grid like this?

**Comment by tomivirkki** [comment]
I wasn't originally able to hook React [Portals](https://github.com/tomivirkki/react-vaadin-components/blob/c1caf95ed6d4ac9b959ea0d3c67df92fd28e9d80/src/Rendered.js#L11) properly with the Grid renderers so settled with [using ReactDOM.render() instead](https://github.com/tomivirkki/react-vaadin-components/blob/c1caf95ed6d4ac9b959ea0d3c67df92fd28e9d80/src/Grid.js#L29), which isn't an ideal solution. Anything you add in the Grid cells is currently rendered with separate `ReactDOM.render()` calls so the cell content might have issues in co-operating with the host app. My guess is that's the cause of the problems.

**Comment by mira-t** [comment]
Thanks for the explanation!
