### ISSUE TITLE
Include a `dist` folder in the repo

### ISSUE THREAD

**Issue by nanopils** [tomivirkki/react-vaadin-components#2]
Hi,

As mentioned in the [Failing unit tests](https://github.com/tomivirkki/react-vaadin-components/issues/1) ticket, our Jest unit tests have ceased to work since using this repository. Also, we noticed that it makes IE11 crash.

Both issues are related to transpiling of ES6, so babel seems to be where the problem lies.

But instead of having to change the babel config in our project, it would great to be able to import transpiled versions of the components. If the transpiled code could be placed in a parallel dist (or build) folder, I think it would simplify the use of the library for many other as well.

Many thanks for this. :)

**Comment by tomivirkki** [comment]
Fixed the mentioned IE11 issue in [0.8.1](https://www.npmjs.com/package/react-vaadin-components/v/0.8.1)

**Comment by nanopils** [comment]
HI,

I have tested v0.8.1, but the same error occurs in IE11, unfortunately. It spits out a "Syntax error (JavaScript)" due to the arrow function in the build.

The screenshot of IE dev tools where the error occurs is attached below:

![image 2](https://user-images.githubusercontent.com/1826339/53075473-8f71bc80-34ed-11e9-97a3-b8d37284b2bb.png)

The error is caused in `node_modules/react-vaadin-components/src/custom-elements-es5-adapter.js` because the component is not transpiled, it seems.

Many thanks for your help.

**Comment by tomivirkki** [comment]
Including a dist folder in this repo wouldn't help in the matter as some transitive dependencies (Polymer, webcomponents, Vaadin) ship ES6 only and don't include such a dist folder. ES6-only dependencies should be dealt with by propely configuring the build tool to also include them in the transpilation process.

With react-scripts/Webpack this works out-of-the-box so projects built on top of that setup function well with IE11 also.

As Parcel (1) [doesn't include dependencies in the process](https://github.com/parcel-bundler/parcel/issues/2500) and cannot easily be configured to do so, an [additional build step](https://github.com/tomivirkki/react-webpack-parcel-project/blob/master/package.json#L7) is required to manually pre-transpile the dependencies.
