### ISSUE TITLE
Example using CRA 3?

### ISSUE THREAD

**Issue by ccummings** [tomivirkki/react-vaadin-components#8]
We just tried to get react-vaadin-components working with CRA 3 and weren't able to find a way to make it work. The existing example is using CRA 2.

We ended up going with Next.js so we could customize the Webpack config and still have a sane path to stay upgraded.

**Comment by tomivirkki** [comment]
Hi, what kind of issues you had with CRA 3? Just tried CRA 3.4 & RVC 0.8.3 and it worked ok for me. I did experience some issues with `@snowpack/plugin-webpack` RVC 0.8.3 though so just published 0.8.4 with [this fix](https://github.com/tomivirkki/react-vaadin-components/commit/74c9a959f893d3ec7fd34f5bb9ef5292748f2bd0). Please see if it help in this case also.

**Comment by ccummings** [comment]
This fixed the primary problem with CRA. It was a problem I still had with Next but in that environment, I was at least able to run the app. Now everything is 👌

Thanks for the fixes!
